{% set name = "fontmath" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 1fd9190c9d784e1305c3c49771b91d910f246a4b7c44ede219c99a07ed7aeda4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - fonttools >=3.32.0
    - python >=3.7

test:
  imports:
    - fontMath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robotools/fontMath
  summary: A set of objects for performing math operations on font data.
  license: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - jan-janssen
