{% set name = "fontmath" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fontMath-{{ version }}.zip
  sha256: 6a5387cb7feb105958db2f5ceedc878513cc35bf3715e262090f0557be0c1b1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - fonttools >=3.32.0
    - python >=3.7

test:
  imports:
    - fontMath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robotools/fontMath
  summary: A set of objects for performing math operations on font data.
  license: MIT
  license_file: License.txt

extra:
  recipe-maintainers:
    - jan-janssen
